# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:

  build:
    runs-on: ${{ matrix.os }}

    env:
        # prefix before commands - used for wine, there the prefix is "wine"
        cPREFIX: ""
        # command to launch python interpreter (its different on macOs, there we need python3)
        cPYTHON: "python"
        # command to launch pip (its different on macOs, there we need pip3)
        cPIP: "python -m pip"
        # switch off wine fix me messages
        WINEDEBUG: fixme-all

        # PYTEST
        PYTEST_DO_TESTS: "True"

        # FLAKE8 tests
        DO_FLAKE8_TESTS: "True"

        # MYPY tests
        MYPY_DO_TESTS: "True"
        MYPY_OPTIONS: "--follow-imports=normal --implicit-reexport --no-warn-unused-ignores --strict"
        MYPYPATH: "./cli_exit_tools/3rd_party_stubs"

        # coverage
        DO_COVERAGE: "True"
        DO_COVERAGE_UPLOAD_CODECOV: "True"
        DO_COVERAGE_UPLOAD_CODE_CLIMATE: "True"
        TRAVIS_TEST_RESULT: "0"

        # package name
        PACKAGE_NAME: "cli_exit_tools"
        # the registered CLI Command
        CLI_COMMAND: "cli_exit_tools"
        # the source file for rst_include (rebuild rst file includes)
        RST_INCLUDE_SOURCE: "./.docs/README_template.rst"
        # the target file for rst_include (rebuild rst file includes)
        RST_INCLUDE_TARGET: "./README.rst"
        # make Code Coverage Secret available in Environment
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        # make PyPi Password available in Environment
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}


    strategy:
      matrix:
        include:
          - os: windows-latest
            python-version: 3.9
            env:
              cEXPORT: "SET"
              BUILD_DOCS: "False"
              DEPLOY_SDIST: "False"
              DEPLOY_WHEEL: "False"
              DEPLOY_TEST: "False"
              MYPY_DO_TESTS: "True"

          - os: ubuntu-latest
            python-version: 3.6
            env:
              BUILD_DOCS: "False"
              DEPLOY_SDIST: "True"
              DEPLOY_WHEEL: "True"
              DEPLOY_TEST: "True"
              MYPY_DO_TESTS: "True"

          - os: ubuntu-latest
            python-version: 3.7
            env:
              BUILD_DOCS: "False"
              DEPLOY_SDIST: "True"
              DEPLOY_WHEEL: "False"
              DEPLOY_TEST: "True"
              MYPY_DO_TESTS: "True"

          - os: ubuntu-latest
            python-version: 3.8
            env:
              BUILD_DOCS: "True"
              DEPLOY_SDIST: "True"
              DEPLOY_WHEEL: "True"
              DEPLOY_TEST: "True"
              MYPY_DO_TESTS: "True"

          - os: ubuntu-latest
            python-version: 3.9
            env:
              BUILD_DOCS: "False"
              DEPLOY_SDIST: "True"
              DEPLOY_WHEEL: "True"
              DEPLOY_TEST: "True"
              MYPY_DO_TESTS: "True"

          - os: ubuntu-latest
            python-version: pypy-3.7
            env:
              BUILD_DOCS: "False"
              DEPLOY_SDIST: "True"
              DEPLOY_WHEEL: "True"
              DEPLOY_TEST: "True"
              MYPY_DO_TESTS: "False"

          - os: macos-latest
            python-version: 3.9
            env:
              cPREFIX: ""               # prefix before commands - used for wine, there the prefix is "wine"
              cPYTHON: "python3"        # command to launch python interpreter (its different on macOs, there we need python3)
              cPIP: "python3 -m pip"    # command to launch pip (its different on macOs, there we need pip3)
              BUILD_DOCS: "False"
              DEPLOY_SDIST: "False"
              DEPLOY_WHEEL: "False"
              DEPLOY_TEST: "True"
              MYPY_DO_TESTS: "True"

    name: "${{ matrix.os }} Python ${{ matrix.python-version }}"

    steps:
    # see : https://github.com/actions/checkout
    - uses: actions/checkout@v2

    - name: Setting up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      # see: https://github.community/t/github-actions-new-bug-unable-to-create-environment-variables-based-matrix/16104/3
      env: ${{ matrix.env }}             # make matrix env variables accessible
      run: |
        ${{ env.cPIP }} install lib_travis
        log_util --colortest
        lib_travis install

    - name: TestScript
      env:
        # make matrix env variables accessible
        ${{ matrix.env }}

      run: |
        log_util --level=NOTICE --banner "working on branch $BRANCH"
        log_util --level=NOTICE --banner "GITHUB_REF $GITHUB_REF"
        # export for current step
        export "BRANCH=$(lib_travis get_branch)"
        # export for subsequent steps
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        log_util --level=NOTICE --banner "github.event.release.tag_name : ${{ github.event.release.tag_name }}"
        log_util --level=NOTICE --banner "github.event.release.name: ${{ github.event.release.name }}"
        log_util --level=NOTICE --banner "github.event.release.body: ${{ github.event.release.body }}"
        log_util --level=NOTICE --banner "github.repository: ${{ github.repository }}"
        # run the tests
        lib_travis script

    - name: After Success
      env:
        ${{matrix.env }}
      shell: bash
      run: |
        lib_travis after_success

    - name: Deploy
      env:
        # see: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        # TRAVIS_TAG: ${{ github.event.release.tag_name }}
        # ${{ github.event.release.tag_name }}
        # ${{ github.event.release.name }}
        # ${{ github.event.release.body }}
        # ${{ github.repository }}

        # make matrix env variables accessible
        ${{matrix.env }}
      shell: bash
      run: |
        lib_travis deploy
        ls -l ./dist
